[workspace.package]
#name = "buenojs"
version = "0.0.1"
edition = "2021"
license = "MIT"
authors = ["The Bueno Team"]
repository = "https://github.com/buenojs/bueno"

[workspace]
resolver = "2"
members = ["ext", "bueno"]

[workspace.dependencies]
deno_core = "0.208.0"
deno_ast = { version = "0.28.0", features = ["transpiling"] }
tokio = { version = "1.19.2", features = ["full"] }
reqwest = { version = "0.11.20" }

bueno_ext = { path = "./ext/" }
