[workspace.package]
version = "0.0.1"
name = "buenojs"
edition = "2021"
license = "MIT"
authors = ["The Bueno Team"]
repository = "https://github.com/buenojs/bueno"

[workspace]
resolver = "2"
members = ["ext", "bueno"]

[workspace.dependencies]
deno_core = "0.214.0"
deno_ast = { version = "0.29.3", features = ["transpiling"] }
tokio = { version = "1.19.2", features = ["full"] }
imara-diff = "0.1.5"
owo-colors = "3.5.0"

bueno_ext = { path = "./ext/" }
